apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ollama-route
  namespace: codegen-poc
spec:
  host: ollama.apps.collective.aws.red-chesterfield.com
  port:
    targetPort: 11434
  to:
    kind: Service
    name: ollama-svc
    weight: 100
  wildcardPolicy: None
