apiVersion: v1
kind: ConfigMap
metadata:
  name: json-configmap
  namespace: codegen-poc
data:
  models_config.json: |-
    {
        "host": "0.0.0.0",
        "port": 8001,
        "models": [
            {
                "model": "/locallm/models/model.file",
                "model_alias": "granite",
                "chat_format": "openchat"
            }
        ]
    }
